# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  id-token: write
  contents: read
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present
      # Configure AWS credentials
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::922372995423:role/GitHubActionsOidcRole
          role-session-name: github-portfolio
          aws-region: us-east-1
      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws s3 sync out s3://iprateek.in
          aws cloudfront create-invalidation --distribution-id E3I2HOXQEGLV8E --path /*
